### ISSUE TITLE
Register of NZ Ruby companies/freelancers

### ISSUE THREAD

**Issue by isaacfreeman** [rubynz/www#8]
Back int he days when I was working primarily on Drupal sites as a freelancer/small company, I got a lot of enquiries by being listed on drupal.org.nz. It'd be great to have something similar for Rubyists.

I'll need to discuss this with the rest of Resolve for resourcing, but I'd be keen to work on this. It would need:
- a form to submit your details, with some thought put into what fields would be most useful for potential clients
- listing pages
- a search tool

It'd probably also be worth looking at what existing sites are already in this space. Once it's built, it might also be a good idea to promote it to recruiting agencies.

**Comment by parndt** [comment]
We used to have this up for everyone at http://rubyonrails.co.nz ...

**Comment by isaacfreeman** [comment]
Ah, predates my time at Resolve. I wonder whether we still have a copy of the database.

**Comment by parndt** [comment]
It would also be useful if we redirected the http://rubyonrails.co.nz URL to point to wherever on http://ruby.org.nz this will now be located, or wherever it ends up.  :smile:

**Comment by isaacfreeman** [comment]
I'll raise it on our Slack and see what people think. Personally I read .co.nz as completely different from .org.nz and would expect to find a company there. But I'm old enough to have formed my views before the .com boom, so perhaps I'm in a minority now.

**Comment by parndt** [comment]
You can see previous revisions of this site over at archive.org - it has always been a pretty useful community resource (since 2009) and only relatively recently did it start redirecting :cry::

https://web.archive.org/web/20090419174143/http://rubyonrails.co.nz/
https://web.archive.org/web/20120418142222/http://rubyonrails.co.nz/

**Comment by isaacfreeman** [comment]
Looks like it shifted to linking to http://www.workingwithrails.com which is now itself retired.

**Comment by isaacfreeman** [comment]
Re http://rubyonrails.co.nz: we want to keep it for Resolve.

**Comment by malclocke** [comment]
@isaacfreeman I'd suggest sending a PR to add a page / some pages to this site with a link at the bottom 'Send a PR to add you company'.  You could pre populate the list with 90% of the companies, and it won't be a big list so I'd say a search tool would be overkill.

**Comment by isaacfreeman** [comment]
Good call @malclocke. Keeps it simple.

**Comment by steveh** [comment]
Closing in favour of #10. This got a bit lost, I've raised it with the (current) committee. I'm also now wathcing this repo :)
